### ISSUE TITLE
Version 0.13.0 doesn't initiate firebase-admin.

### ISSUE THREAD

**Issue by egisz** [gladly-team/next-firebase-auth#161]
**Describe the bug**
Version 0.12.2  works fine, next build finishes fine.
After upgrade to 0.13.0, I get error: 
```
$next build
....
info  - Creating an optimized production build  
info  - Compiled successfully

Build error occurred
Error: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.
    at FirebaseAppError.FirebaseError [as constructor] (/home/bot/trip-finder/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/home/bot/trip-finder/node_modules/firebase-admin/lib/utils/error.js:90:28)
    at new FirebaseAppError (/home/bot/trip-finder/node_modules/firebase-admin/lib/utils/error.js:125:28)
    at FirebaseNamespaceInternals.app (/home/bot/trip-finder/node_modules/firebase-admin/lib/firebase-namespace.js:97:19)
    at FirebaseNamespace.app (/home/bot/trip-finder/node_modules/firebase-admin/lib/firebase-namespace.js:365:30)
    at FirebaseNamespace.ensureApp (/home/bot/trip-finder/node_modules/firebase-admin/lib/firebase-namespace.js:379:24)
    at FirebaseNamespace.fn (/home/bot/trip-finder/node_modules/firebase-admin/lib/firebase-namespace.js:239:30)
    at getLocationSlugs (/home/bot/trip-finder/.next/server/pages/location/[location].js:5324:87)
    at getStaticPaths (/home/bot/trip-finder/.next/server/pages/location/[location].js:7226:72)
    at buildStaticPaths (/home/bot/trip-finder/node_modules/next/dist/build/utils.js:16:86) {
  type: 'FirebaseAppError',
  errorInfo: {
    code: 'app/no-app',
    message: 'The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.'
  },
  codePrefix: 'app'
}
error Command failed with exit code 1.
```

**Version**
0.12.2 - works fine
0.13.0 - fails

**To Reproduce**
`$next build`

**Expected behavior**

**Additional context**
My ininAuth.js file:
```
import { init } from 'next-firebase-auth';
import { HOME_PAGE, LOGIN_PAGE, API_LOGIN, API_LOGOUT } from 'settings/constant';

const TWELVE_DAYS_IN_MS = 12 * 60 * 60 * 24 * 1000;

const initAuth = () => {
  init({
    debug: false,
    authPageURL: LOGIN_PAGE,
    appPageURL: HOME_PAGE,
    loginAPIEndpoint: API_LOGIN,
    logoutAPIEndpoint: API_LOGOUT,
    firebaseAdminInitConfig: {
      credential: {
        projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
        clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
        // Using JSON to handle newline problems when storing the
        // key as a secret in Vercel. See:
        // https://github.com/vercel/vercel/issues/749#issuecomment-707515089
        privateKey: process.env.FIREBASE_PRIVATE_KEY ? JSON.parse(process.env.FIREBASE_PRIVATE_KEY) : undefined,
      },
      databaseURL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
    },
    firebaseClientInitConfig: {
      apiKey: process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY,
      authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
      projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
      storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
      messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
      appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
      measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
    },
    cookies: {
      name: 'authorization',
      keys: [process.env.COOKIE_SECRET_CURRENT, process.env.COOKIE_SECRET_PREVIOUS],
      httpOnly: true,
      maxAge: TWELVE_DAYS_IN_MS,
      overwrite: true,
      path: HOME_PAGE,
      sameSite: 'strict',
      secure: process.env.NEXT_PUBLIC_COOKIE_SECURE === 'true',
      signed: true,
    },
  });
};

export default initAuth;

```

**Comment by shreyas-jadhav** [comment]
If you're using intializing firebase admin manually, can you share the code where you initialize firebase admin?

**Comment by egisz** [comment]
My bad, I wasn't initializing firebase server side, only client side, in _app.js. Server side getStaticPaths is called before rendering, so it hasn't initiated firebase Admin SDK. This page did not include initAuth locally.

I was only importing admin from firebase-admin:
`import * as admin from 'firebase-admin';`

Weird thing that it worked fine on 0.12.2, but stopped working on 0.13. I updated code, included imports and called initAuth before using admin SDK and it works again with 0.13.
Updated code.: 
```
// file: library/firebase/firebaseAdmin.js
// import * as admin from 'firebase-admin'
import { getFirebaseAdmin } from 'next-firebase-auth';
import initAuth from 'library/firebase/initAuth';

const admin = getFirebaseAdmin();

// failing function: 
export const getLocationSlugs = async () => {
  // initAuth();
  const querySnapshot = await admin.firestore().collection('locations').select().get();
<...>
  return result;
};
```

Any clue why it worked before? If no, then we can close this issue.

**Comment by mfyz** [comment]
I am getting same error even though I do call initAuth on my API handlers. 

Weird thing is, this works perfectly in my local and it does give error randomly on vercel. The issue is not persistent in specific endpoint. But my app does make 4-5 API calls to different endpoints and at least 2 of them give this error. Strangely, in every page refresh different endpoints giving this error.

It feels like init() method (that is being called in initAuth method I have it in utils - as the sample code does) take longer to initialize until the verifyIdToken method is being called.

Here is my API handler (one of them):
```
import { verifyIdToken } from 'next-firebase-auth'
import initAuth from '../../../../utils/init-auth'
import db from '../../../../utils/init-firestore'

initAuth()

export default async (req, res) => {
	if (req.method !== 'POST') return res.status(400).json({ error: 'Must be DELETE request' })
	
	if (!(req.headers && req.headers.authorization)) {
		return res.status(400).json({ error: 'Missing Authorization header value' })
	}
	const token = req.headers.authorization
	let authUser = {}
	try {
		authUser = await verifyIdToken(token)
	} catch (e) {
		console.error(e)
		return res.status(403).json({ error: 'Not authorized' })
	}

	// Check permission
	const projectQuery = await db.collection('projects').doc(req.query.editProjectId).get()
	const project = projectQuery.data()
	if (!(project && project.active)) {
		return res.status(404).json({ error: `Project not found.` })
	}
	if (project.owner_user_id !== authUser.id) {
		return res.status(403).json({ error: `You are not the owner of this project.` })
	}

	// Validation
	const errors = []
	if (!req.body.name) errors.push('Project name is required')
	if (errors.length > 0) {
		return res.json({ errors })
	}

	// Update fields
	project.name = req.body.name
	if (req.body.color) project.color = req.body.color
	project.updated_at = new Date().toISOString()
	
	await db.collection('projects').doc(req.query.editProjectId).set(project)

	return res.status(200).json({ success: true })
}
```

And here is the initAuth:
```
import { init } from 'next-firebase-auth'

const TWELVE_DAYS_IN_MS = 12 * 60 * 60 * 24 * 1000

const initAuth = () => {
	init({
		debug: false,
		authPageURL: '/signin',
		appPageURL: '/',
		loginAPIEndpoint: '/api/login',
		logoutAPIEndpoint: '/api/logout',
		firebaseAdminInitConfig: {
			credential: {
				projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
				clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
				privateKey: process.env.FIREBASE_PRIVATE_KEY
					? JSON.parse(process.env.FIREBASE_PRIVATE_KEY)
					: undefined,
			},
			databaseURL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
		},
		firebaseClientInitConfig: {
			apiKey: process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY,
			authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
			databaseURL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
			projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
		},
		cookies: {
			name: 'Featuristik',
			keys: [
				process.env.COOKIE_SECRET_CURRENT,
				process.env.COOKIE_SECRET_PREVIOUS,
			],
			httpOnly: true,
			maxAge: TWELVE_DAYS_IN_MS,
			overwrite: true,
			path: '/',
			sameSite: 'strict',
			secure: process.env.NEXT_PUBLIC_COOKIE_SECURE === 'true',
			signed: true,
		},
	})
}

export default initAuth
```

And here is what I get in vercel function logs:
```
...
qos1Xlu7vQ3Lg0qVpOmPUir5+X4Hdez64ovEEwsu4cWR445Pnf0vf+R3mkeQ8fF1
vuPzAgomhe12o+K6zYtfMOL8
-----END PRIVATE KEY-----'
    at FirebaseAppError.FirebaseError [as constructor] (/var/task/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/var/task/node_modules/firebase-admin/lib/utils/error.js:90:28)
    at new FirebaseAppError (/var/task/node_modules/firebase-admin/lib/utils/error.js:125:28)
    at Function.ServiceAccount.fromPath (/var/task/node_modules/firebase-admin/lib/credential/credential-internal.js:151:19)
    at new ServiceAccountCredential (/var/task/node_modules/firebase-admin/lib/credential/credential-internal.js:67:28)
    at Object.exports.cert (/var/task/node_modules/firebase-admin/lib/credential/credential.js:34:54)
    at Object.5847 (/var/task/.next/server/pages/api/feature/list/[...featureListParams].js:148:64)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
    at Object.2896 (/var/task/.next/server/pages/api/feature/list/[...featureListParams].js:15:79)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
2021-05-30T17:49:17.248Z	890c23a8-65bc-4a16-bba9-aa40b7c52ba9	ERROR	FirebaseAppError: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.
    at FirebaseAppError.FirebaseError [as constructor] (/var/task/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/var/task/node_modules/firebase-admin/lib/utils/error.js:90:28)
    at new FirebaseAppError (/var/task/node_modules/firebase-admin/lib/utils/error.js:125:28)
    at FirebaseNamespaceInternals.app (/var/task/node_modules/firebase-admin/lib/firebase-namespace.js:97:19)
    at FirebaseNamespace.app (/var/task/node_modules/firebase-admin/lib/firebase-namespace.js:381:30)
    at FirebaseNamespace.ensureApp (/var/task/node_modules/firebase-admin/lib/firebase-namespace.js:395:24)
    at FirebaseNamespace.fn (/var/task/node_modules/firebase-admin/lib/firebase-namespace.js:239:30)
    at Object.5847 (/var/task/.next/server/pages/api/feature/list/[...featureListParams].js:156:86)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
    at Object.2896 (/var/task/.next/server/pages/api/feature/list/[...featureListParams].js:15:79) {
  errorInfo: {
    code: 'app/no-app',
    message: 'The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.'
  },
  codePrefix: 'app'
}
RequestId: 890c23a8-65bc-4a16-bba9-aa40b7c52ba9 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

I do not initialize firebase admin manually. I use init method of this package as you can see in initAuth file.

Again, no issues whatsoever on local, but I get this in vercel.

**Comment by kmjennison** [comment]
@mfyz Interesting. I assume the error occurs when you call `verifyIdToken`? Are you interacting with Firebase admin anywhere else? I wouldn't expect any race condition in this package, because the admin app initialization is synchronous and happens [when calling verifyIdToken](https://github.com/gladly-team/next-firebase-auth/blob/main/src/firebaseAdmin.js#L58).
