### ISSUE TITLE
Unable to set private key

### ISSUE THREAD

**Issue by jinwood** [gladly-team/next-firebase-auth#239]
Hi, new to nextjs and Firebase. I hope this is a valid issue.

I'm trying to get started with the authentication template. I have it mostly setup.

My issue is that firebase does not seem to happy with the private key value I am giving it on init.

I'm base64 encoding my private key, decoding it, and loading into the init function in `initAuth.js`.

I'm logging the decoded json into the console and the private key property clearly exists. But I'm getting this error that the value is missing. 

`initAuth.js`
```
const privateKeyBase64 = process.env.FIREBASE_PRIVATE_KEY;
let buffer, privateKey;
if (privateKeyBase64) {
  buffer = Buffer.from(privateKeyBase64, "base64");
  privateKey = buffer.toString("utf-8");
  console.log(privateKey);
}

init({
  // ...
  privateKey: privateKey ? JSON.parse(privateKey) : undefined,
});

```

The `console.log()` output looks like this (with sensitive stuff removed).
```
{
  "type": "service_account",
  "project_id": "",
  "private_key_id": "",
  "private_key": "-----BEGIN PRIVATE KEY----- STUFF \n-----END PRIVATE KEY-----\n",
  "client_email": "",
  "client_id": "",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": ""
}
```

This is the error I get:

> FirebaseAppError: Service account object must contain a string "private_key" property.
    at FirebaseAppError.FirebaseEr-admin/lib/utils/error.js:44:28) at FirebaseAppError.PrefixedFirebaseError [as constructor] (/home/node_modules/firebase-admin/lib/utils/error.js:90:28) at new FirebaseAppError (/home/node_modules/firebase-admin/lib/utils/error.js:125:28) at new ServiceAccount (/home/node_modules/firebase-admin/lib/credential/credential-internal.js:134:19) at new ServiceAccountCredential (/home/node_modules/firebase-admin/lib/credential/credential-internal.js:68:15) aror [as constructor] (/home/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/home/node_modules/firebase-admin/lib/utils/error.js:90:28)
    at new FirebaseAppError (/home/node_modules/firebase-admin/lib/utils/error.js:125:28)
    at new ServiceAccount (/home/node_modules/firebase-admin/lib/credential/credential-internal.js:134:19)
    at new ServiceAccountCredential (/home/node_modules/firebase-admin/lib/credential/credential-internal.js:68:15)
    at Object.exports.cert (/home/node_modules/firebase-admin/lib/credential/credential.js:34:54)
    at z (/home/node_modules/next-firebase-auth/build/index.node.js:2:16085)
    at /home/node_modules/next-firebase-auth/build/index.node.js:2:16932
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/me/project/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24) {
  errorInfo: {
    code: 'app/invalid-credential',
    message: 'Service account object must contain a string "private_key" property.'
  },
  codePrefix: 'app'

**Version**
0.13.2

Thanks

**Comment by jinwood** [comment]
Sorted, was being thick and not providing the privateKey property of the key json.
