### ISSUE TITLE
Usage without private key causes an error 

### ISSUE THREAD

**Issue by fabienheureux** [gladly-team/next-firebase-auth#434]
**Describe the bug**
My GCP policy does not allow using service account private key to authenticate with firebase.
The authentication should be automatic through GCP infrastructure, and I don't have a public/private key pair.
  
I tried setting up this module without the admin config, but every time I get an error 
```
TypeError: Cannot read properties of undefined (reading 'credential')
```

I tried versions 0.x of this package and firebase 8, without success. 

**Versions**

`next-firebase-auth` version: v1.0.0-canary.6 
Firebase JS SDK: 9.6.6
Next.js: 12.010

**To Reproduce**
1. Iinitialize the module with this object
```js

const firebaseClientInitConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

const initAuth = () => {
    init({
        authPageURL: '/auth',
        appPageURL: '/',
        loginAPIEndpoint: '/api/login', // required
        logoutAPIEndpoint: '/api/logout', // required
        onLoginRequestError: (err) => {
            console.error(err);
        },
        onLogoutRequestError: (err) => {
            console.error(err);
        },
        firebaseAuthEmulatorHost: 'localhost:9099',
        useFirebaseAdminDefaultCredential: true,
        firebaseClientInitConfig,
        cookies: {
            name: 'MyCookieName', // required
            httpOnly: true,
            maxAge: 12 * 60 * 60 * 24 * 1000, // twelve days
            overwrite: true,
            path: '/',
            sameSite: 'strict',
            secure: false,
            // secure: process.env.NODE_ENV !== 'development',
            signed: false,
            // signed: process.env.NODE_ENV !== "development",
            // Keys are required unless you set `signed` to `false`.
            // The keys cannot be accessible on the client side.
            // keys: [
            //     process.env.COOKIE_SECRET_CURRENT,
            //     process.env.COOKIE_SECRET_PREVIOUS,
            // ],
        },
        onVerifyTokenError: (err) => {
            console.error(err);
        },
        onTokenRefreshError: (err) => {
            console.error(err);
        },
    } as any);
};
```

**Expected behavior**
It should work ? I am not sure. 

**Additional context**
Here is "full stacktrace", not very relevant though  
```
TypeError: Cannot read properties of undefined (reading 'credential')
    at v (/path/node_modules/next-firebase-auth/build/index.node.js:2:9502)
    at b (/path/node_modules/next-firebase-auth/build/index.node.js:2:9682)
    at Object.init (/path/node_modules/next-firebase-auth/build/index.node.js:2:17586)
    at init (/path/node_modules/next-firebase-auth/build/index.node.js:2:27241)
    at initAuth (webpack-internal:///./lib/initAuth.ts:17:61)
    at eval (webpack-internal:///./pages/_app.tsx:44:59) {
  page: '/'
}
```

**Comment by kmjennison** [comment]
Did you set [`useFirebaseAdminDefaultCredential`](https://github.com/gladly-team/next-firebase-auth#usefirebaseadmindefaultcredential) to true?

**Comment by fabienheureux** [comment]
Thanks for your reply, I don't know why it is not in the config in my initial issue, but yes I did.
I will try to create a minimal example

**Comment by fabienheureux** [comment]
Here is the example repo @kmjennison https://github.com/fabienheureux/next-firebase-auth-example

**Comment by kmjennison** [comment]
@fabienheureux Thanks for the clear reproduction! I identified a bug where the library assumed a Firebase credential will be set. Fixing now.

**Comment by fabienheureux** [comment]
Wow thanks for the quick response and fix ! This is awesome.

**Comment by kmjennison** [comment]
You're welcome! Just released the fix in the latest preview versions. Let me know if you run into any additional problems.
