### ISSUE TITLE
Firebase-admin auth token-generator.js ERR_OSSL_PEM_NO_START_LINE on `yarn build && yarn start`

### ISSUE THREAD

**Issue by AkromDev** [gladly-team/next-firebase-auth#441]
**Describe the bug**

I am getting an error in production mode locally. 
When I run the project using `yarn dev`, everything is working great. 
But if I build the project by running `yarn build` and running by `yarn start`, I am getting error below. 
`Error: 16 UNAUTHENTICATED: Failed to retrieve auth metadata with error: error:0909006C:PEM routines:get_name:no start line`.

Do I need to provide any extra configuration for production mode?

Things I tried:
I am wrapping private key as described in documentation 
`FIREBASE_PRIVATE_KEY='"-----BEGIN PRIVATE KEY-----\nMIIEvgIB\n-----END PRIVATE KEY-----\n"'`

I also tried  replacing `        
privateKey: process.env.FIREBASE_PRIVATE_KEY
          ? JSON.parse(process.env.FIREBASE_PRIVATE_KEY)
          : undefined,` code with `privateKey: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n') || ''` in `firebaseAdminInitConfig` but it did not help.

I am getting the same error in deployed version on vercel. I added env variables as per instruction in env.example file.
`vercel secrets add firebase-private-key '"my-key-here"'`

Detailed error message:

Error: 16 UNAUTHENTICATED: Failed to retrieve auth metadata with error: error:0909006C:PEM routines:get_name:no start line
    at Object.callErrorFromStatus (/Users/akramjonmamasoliev/Developer/web/bike-rentals-submission/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/akramjonmamasoliev/Developer/web/bike-rentals-submission/node_modules/@grpc/grpc-js/build/src/client.js:331:49)
    at Object.onReceiveStatus (/Users/akramjonmamasoliev/Developer/web/bike-rentals-submission/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /Users/akramjonmamasoliev/Developer/web/bike-rentals-submission/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Caused by: Error
    at Query._get (/Users/akramjonmamasoliev/Developer/web/bike-rentals-submission/node_modules/@google-cloud/firestore/build/src/reference.js:1519:23)
    at Query.get (/Users/akramjonmamasoliev/Developer/web/bike-rentals-submission/node_modules/@google-cloud/firestore/build/src/reference.js:1507:21)
    at /Users/akramjonmamasoliev/Developer/web/bike-rentals-submission/.next/server/pages/profile.js:258:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 16,
  details: 'Failed to retrieve auth metadata with error: error:0909006C:PEM routines:get_name:no start line',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

**Versions**

`next-firebase-auth` version: 
"next-firebase-auth": "^1.0.0-canary.5",

Firebase JS SDK:
 "firebase": "^9.6.7",
"firebase-admin": "^10.0.2",

Next.js: 
"next": "12.0.7",

Operating system: MAC OS Monterey, Intel chip

**To Reproduce**
1. Set up the the project as instructed with the above versions.
2. Add env files
3. yarn build && yarn start

**Comment by kmjennison** [comment]
It looks like your private key isn't formatted correctly. See different approaches to private key formatting here:
https://github.com/gladly-team/next-firebase-auth#i-get-the-error-failed-to-parse-private-key-error-invalid-pem-formatted-message
